
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";
import { SEOHead } from "@/components/landing/SEOHead";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <SEOHead
        title="Terms of Service – AI Writer Pros"
        description="Read the AI Writer Pros terms of service. Understand the rules and guidelines for using our AI writing tools."
        canonical="https://aiwriterpros.com/terms-of-service"
      />
      <Navigation />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 lg:py-24">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-10">Last updated: February 11, 2026</p>

        <div className="prose prose-lg max-w-none text-muted-foreground space-y-8">
          <section>
            <h2 className="text-2xl font-semibold text-foreground">1. Agreement to Terms</h2>
            <p>
              By accessing or using AI Writer Pros ("the Service"), you agree to be bound by these Terms of 
              Service. If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">2. Description of Service</h2>
            <p>
              AI Writer Pros provides AI-powered writing tools including blog content creation, email 
              generation, social media content creation, AI humanization, content repurposing, and 
              Amazon affiliate review tools. The Service is provided "as is" and "as available."
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">3. User Accounts</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>You must provide accurate and complete registration information</li>
              <li>You are responsible for maintaining the security of your account credentials</li>
              <li>You must notify us immediately of any unauthorized use of your account</li>
              <li>You must be at least 16 years old to create an account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">4. Content Ownership</h2>
            <p>
              You retain all ownership rights to content you create using our tools. By using the Service, 
              you grant us a limited license to process your input content solely for the purpose of 
              providing the Service to you. We do not claim ownership of any content you generate.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Generate content that is illegal, harmful, threatening, abusive, or defamatory</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on the intellectual property rights of others</li>
              <li>Generate spam, phishing content, or malicious material</li>
              <li>Attempt to reverse-engineer, decompile, or disassemble the Service</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Create content that promotes discrimination or hatred</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">6. Subscription & Payments</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Some features require a paid subscription</li>
              <li>Prices are subject to change with reasonable notice</li>
              <li>Subscriptions renew automatically unless cancelled</li>
              <li>Refunds are handled on a case-by-case basis</li>
              <li>Free tier usage is subject to fair use limitations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">7. AI-Generated Content Disclaimer</h2>
            <p>
              Content generated by our AI tools is provided as a starting point and should be reviewed 
              before publication. We do not guarantee the accuracy, completeness, or originality of 
              AI-generated content. You are responsible for reviewing, editing, and fact-checking 
              all content before use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, AI Writer Pros shall not be liable for any indirect, 
              incidental, special, consequential, or punitive damages, or any loss of profits or revenues, 
              whether incurred directly or indirectly, or any loss of data, use, goodwill, or other 
              intangible losses resulting from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless AI Writer Pros from any claims, damages, losses, 
              or expenses arising from your use of the Service, your violation of these Terms, or your 
              violation of any rights of another party.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">10. Termination</h2>
            <p>
              We may terminate or suspend your account at any time for violation of these Terms. Upon 
              termination, your right to use the Service will immediately cease. You may also delete 
              your account at any time through your profile settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">11. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of material 
              changes via email or through the Service. Your continued use of the Service after changes 
              constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable laws, 
              without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">13. Contact Us</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us at{" "}
              <a href="mailto:support@aiwriterpros.com" className="text-primary hover:underline">
                support@aiwriterpros.com
              </a>.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
