
import { ArticleLayout } from "@/components/kb/ArticleLayout";
import { Shield } from "lucide-react";
import { Link } from "react-router-dom";

export default function KBPatternAnalyzer() {
  return (
    <ArticleLayout
      title="How the AI Pattern Analyzer Works"
      description="Understand how the AI Writer Pros pattern analyzer detects AI-generated content, provides detection confidence scores, and identifies specific phrases that trigger AI detectors."
      category="AI Humanizer"
      categoryIcon={Shield}
      readTime="5 min read"
      keywords="AI detection, AI pattern analyzer, AI content detection score, GPTZero alternative, AI writing detection"
      nextArticle={{ title: "Humanization Intensity", link: "/knowledge-base/humanization-intensity" }}
    >
      <h2>What Is the AI Pattern Analyzer?</h2>
      <p>
        The AI Pattern Analyzer is a <strong>pre-humanization diagnostic tool</strong> built into the AI Humanizer. Before you humanize any content, it scans your text and provides a detailed report showing how likely it is to be flagged as AI-generated by popular detection tools.
      </p>

      <h2>How to Use the Analyzer</h2>
      <h3>Step 1: Paste Your Content</h3>
      <p>
        Enter or paste the content you want to analyze into the AI Humanizer's input textarea. The analyzer requires a <strong>minimum of 50 words</strong> to produce accurate results. A real-time word counter below the textarea shows your current count.
      </p>

      <h3>Step 2: Click "🔍 Analyze AI Patterns"</h3>
      <p>
        Once your content meets the minimum word count, the <strong>Analyze AI Patterns</strong> button becomes active. Click it to send your content for AI analysis. The process typically takes 3-8 seconds.
      </p>

      <h3>Step 3: Review the Analysis Dashboard</h3>
      <p>After analysis, you'll see a comprehensive dashboard card displaying:</p>
      <ul>
        <li><strong>AI Detection Score (0-100%)</strong> — A confidence score indicating how likely your content is to be flagged as AI-generated. Higher scores mean more AI-like patterns detected.</li>
        <li><strong>Visual Gauge</strong> — Color-coded indicator: red (high AI likelihood), yellow (medium), green (human-like)</li>
        <li><strong>Content Type Badge</strong> — Automatically detected content type (Blog, Academic, Marketing, Technical, or Other)</li>
        <li><strong>Detected Writing Style</strong> — Whether the content reads as Professional, Casual, Technical, or Academic</li>
        <li><strong>AI Patterns Detected</strong> — An expandable list of specific phrases flagged as AI-like, each with an explanation</li>
        <li><strong>Recommended Humanization Level</strong> — A suggested intensity (Light, Medium, or Aggressive) based on the analysis</li>
      </ul>

      <h2>Understanding the Detection Score</h2>
      <h3>Score Ranges</h3>
      <ul>
        <li><strong>0-25% (Green)</strong> — Content appears human-written. Minimal humanization needed, if any.</li>
        <li><strong>26-60% (Yellow)</strong> — Mixed signals. Some AI patterns detected. Light to Medium humanization recommended.</li>
        <li><strong>61-100% (Red)</strong> — Strong AI indicators. Medium to Aggressive humanization recommended for best results.</li>
      </ul>

      <h3>What Gets Flagged?</h3>
      <p>The analyzer identifies patterns that AI detection tools commonly flag:</p>
      <ul>
        <li><strong>Overly formal transitions</strong> — "Furthermore," "Moreover," "It is important to note that"</li>
        <li><strong>Predictable sentence structures</strong> — Consistently similar sentence lengths and patterns</li>
        <li><strong>Generic qualifiers</strong> — "In today's fast-paced world," "It goes without saying"</li>
        <li><strong>Lack of personal voice</strong> — Absence of contractions, colloquialisms, or subjective opinions</li>
        <li><strong>Uniform paragraph length</strong> — AI tends to produce paragraphs of similar size</li>
      </ul>

      <h2>Using Analysis Results Effectively</h2>
      <p>The analysis results <strong>persist until you change the content</strong>, so you can reference them while configuring your humanization settings. Use the results to:</p>
      <ul>
        <li>Set the <strong>Humanization Intensity</strong> slider to the recommended level</li>
        <li>Choose the appropriate <strong>Target Writing Style</strong> based on the detected style</li>
        <li>Focus manual edits on the specific <strong>flagged phrases</strong> if you prefer to fix issues yourself</li>
      </ul>

      <hr />
      <h2>Next Steps</h2>
      <p>Learn how to choose the right humanization intensity for your content: <Link to="/knowledge-base/humanization-intensity">Choosing the Right Humanization Intensity →</Link></p>
    </ArticleLayout>
  );
}
