
import { ArticleLayout } from "@/components/kb/ArticleLayout";
import { CreditCard } from "lucide-react";
import { Link } from "react-router-dom";

export default function KBTeamManagement() {
  return (
    <ArticleLayout
      title="Team Management & Collaboration"
      description="Invite team members, manage roles, and share AI-generated content across your organization with AI Writer Pros team features."
      category="Account & Billing"
      categoryIcon={CreditCard}
      readTime="3 min read"
      keywords="team management, collaboration tools, invite team members, AI writing team, shared workspace"
      prevArticle={{ title: "Profile Settings", link: "/knowledge-base/profile-settings" }}
    >
      <h2>Team Features Overview</h2>
      <p>AI Writer Pros supports <strong>multi-user collaboration</strong> on Business plans, allowing teams and agencies to work together from a shared workspace.</p>

      <h2>Inviting Team Members</h2>
      <ol>
        <li>Navigate to your <Link to="/dashboard/profile">Profile Settings</Link></li>
        <li>Find the <strong>Team Management</strong> section</li>
        <li>Click <strong>"Invite Member"</strong> and enter their email address</li>
        <li>Select their <strong>role</strong> (Admin, Editor, or Viewer)</li>
        <li>They'll receive an invitation email to join your workspace</li>
      </ol>

      <h2>Roles & Permissions</h2>
      <ul>
        <li><strong>Admin</strong> — Full access to all tools, settings, billing, and team management</li>
        <li><strong>Editor</strong> — Access to all AI tools, can create and edit content, cannot manage billing</li>
        <li><strong>Viewer</strong> — Read-only access to generated content, cannot generate or edit</li>
      </ul>

      <h2>Sharing Content</h2>
      <ul>
        <li>All content generated by team members is <strong>visible to the entire team</strong></li>
        <li>Use <strong>favorites and tags</strong> to organize shared content</li>
        <li>Export and download content for use outside the platform</li>
      </ul>

      <h2>Credit Sharing</h2>
      <p>On team plans, credits are <strong>shared across all team members</strong>. Admins can view a breakdown of credit usage by member in the usage dashboard.</p>

      <hr />
      <h2>Next Steps</h2>
      <p>Explore all available tools in the <Link to="/knowledge-base">Knowledge Base</Link> or read the <Link to="/best-practices">Best Practices Guide</Link> for expert tips on team content workflows.</p>
    </ArticleLayout>
  );
}
